---
- hosts: localhost
  connection: local
  vars:
    dotfiles_dir: "dotfiles_dir"
    real_name: Hiroto Takahashi
    email: guild0105@gmail.com
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/cask
      - railwaycat/emacsmacport
      - sanemat/font
    homebrew_packages:
      - { name: readline }
      - { name: openssl }
      - { name: openssl, state: linked, install_options: force }
      - { name: python }
      - { name: ansible }
      - { name: coreutils }
      - { name: git }
      - { name: zsh, install_options: disable-etcdir }
      - { name: zplug }
      - { name: wget }
      - { name: curl }
      - { name: cmake }
      - { name: autoconf }
      - { name: automake }
      - { name: pkg-config }
      - { name: ctags }
      - { name: tree }
      - { name: lv }
      - { name: nkf }
      - { name: jq }
      - { name: go }
      - { name: direnv }
      - { name: peco }
      - { name: hub }
      - { name: tig }
      #- { name: fish }
      - { name: rbenv }
      - { name: ruby-build }
      - { name: tofrodos }
      - { name: lha }
      - { name: flow }
      - { name: mysql }
      - { name: sqlite }
      - { name: redis }
      - { name: imagemagick }
      - { name: mercurial }
      - { name: packer }
      - { name: xz }
      - { name: socat }
      - { name: rlwrap }
      - { name: w3m }
      - { name: tmux }
      - { name: reattach-to-user-namespace }
      - { name: phantomjs }
      - { name: graphviz }
      - { name: autojump }
      - { name: gibo }
      - { name: source-highlight }
    homebrew_cask_packages:
      - { name: emacs-mac }
      - { name: iterm2 }
      - { name: dropbox }
      - { name: firefox }
      - { name: google-chrome }
      - { name: adobe-reader }
      - { name: java }
      - { name: skype }
      - { name: slack }
      - { name: sourcetree }
      - { name: gitx }
      - { name: karabiner }
      - { name: seil }
      - { name: flux }
      # - { name: dash }
      - { name: skitch }
      - { name: seashore }
      - { name: atom }
      - { name: kobito }
      - { name: webstorm }
      - { name: phpstorm }
      - { name: intellij-idea }
      - { name: pycharm }
      - { name: vagrant }
      - { name: virtualbox }
      - { name: bettertouchtool }
      - { name: kindle }

  tasks:
    # Homebrew
    - name: Install Homebrew Dupes
      homebrew_tap: tap=homebrew/dupes
      tags:
        - homebrew
    - name: Upgrade Homebrew and installed Homebrew packages
      homebrew:
        update_homebrew: yes
        upgrade_all: yes
      tags:
        - homebrew
    - name: Install Homebrew packages
      homebrew:
        name: "{{item}}"
      with_items:
        - "{{homebrew_packages}}"
      tags:
        - git
        - homebrew
        - homebrew-cask
        - openssh
        - vim
        - zsh

    # Ricty
    - name: xquartz のインストール (for Ricty)
      homebrew_cask: name=xquartz
    - name: fontforge のインストール (for Ricty)
      homebrew: name=fontforge
    - name: Ricty のインストール
      homebrew: name=ricty
    - name: 生成されたフォントファイルをコピー
      shell: cp -f $(brew --cellar ricty)/*/share/fonts/Ricty*.ttf ~/Library/Fonts/
      args:
        creates: ~/Library/Fonts/Ricty-Bold.ttf
      notify: run fc-cache

    # Homebrew Cask
    - name: Install Homebrew Cask
      homebrew_tap: tap=caskroom/cask
      tags:
        - homebrew-cask

    # git
    - name: Link .gitconfig
      file:
        src: "{{dotfiles_dir}}/.gitconfig"
        dest: ~/.gitconfig
        # mode: 0600
        state: link
      tags:
        - git
    - name: Link .gitignore_global
      file:
        src: "{{dotfiles_dir}}/.gitignore_global"
        dest: ~/.gitignore_global
        # mode: 0600
        state: link
      tags:
        - git

    # vim
    - name: Create symbolic link from vimrc to ~/.vimrc
      file:
        src: "{{dotfiles_dir}}/vimrc"
        dest: ~/.vimrc
        # mode: 0600
        state: link
      tags:
        - vim


  handlers:
    - name: run fc-cache
      shell: fc-cache -vf

